### ISSUE TITLE
Extension is still downloaded from the default repository

### ISSUE THREAD

**Issue by peter-janssen** [gzm55/project-settings-maven-extension#1]
This is probably not a problem of the extension.
I'm to use this extension to set a different repository for downloading artifacts because repo.maven.apache.org is blocked by the corporate proxy. Unfortunately the artifact of the extensions is still downloaded against the default repository.

**Comment by gzm55** [comment]
This is a known issue: https://issues.apache.org/jira/browse/MNG-6392

As you mentioned, this extension just works after the resolving of the global and project level extensions. Now there will be some ways to fix this:

a) push and fix MNG-6392, or
b) put the jar of this extension into `$M2_HOME/lib/ext` dir, or
c) using the maven wrapper with a customized maven distribution binding this ext, or
d) config the corp internal repo url as a mirror of central repo in every developers' `settings.xml`
