### ISSUE TITLE
Property to ignore user/system-settings.xml

### ISSUE THREAD

**Issue by opensource21** [gzm55/project-settings-maven-extension#2]
I had the problem that with user-settings I get repos which I don't want to use in my specific project.
The problem is that if I merge user settings with the project-settings I get the profile of the user-settings not from project-settings.
Is it possible to ignore user-settings.xml or is it a bug?

**Comment by gzm55** [comment]
Even if this extension skips the user settings.xml, the maven itself will still try to load that xml. In addition, the maven will only skip the non-existent default user settings.xml, that is, if you pass user settings by option `mvn -s user-settings.xml`, the specified path must exist.

So there may be two ways to ignore your default user settings.xml:
a) write an empty settings.xml in your project, and call mvn like `mvn -s an-empty-settings-in-project.xml`
b) pass the project settings.xml as user settings: `mvn -s .mvn/settings.xml`

**Comment by opensource21** [comment]
Thanks for the quick-response. This was my first approach by using .mvn/maven.config. The problem with it is, that you can declare an absolute path (which is useless if you commit it) or a relative-path which doesn't work in a multi-project if someone changed in the subdirectory and call mvn .... Then it will result in an error, because it's not relative to mvn.config. 
It looks like I must live with the problem, that each user must copy the right settings.xml to his home or use -s :-(

**Comment by gzm55** [comment]
if using maven wrapper, you can resolve the user settings' absolute path in the wrapper entry script `mvnw`
