### ISSUE TITLE
Custom profiles in .mvn/settings.xml  ignored / not merged

### ISSUE THREAD

**Issue by eva-mueller** [gzm55/project-settings-maven-extension#3]
Hi,

I stumbled upon your extension when searching for a possibility to define and persist
custom Maven profiles outside the production code.

Unfortunately, profiles won't get merged by this extension and thus are not available.
But maybe I configured it wrong?
* Added extension to `.mvn/extensions.xml`
* Added `.mvn/settings.xml` with custom profile

Are there plans to extend this extension to merge additional profiles via the `.mvn/settings.xml`?

Thanks in advance

**Comment by gzm55** [comment]
profiles in .mvn/settings.xml should already work, at least in my production codes. Could you plz provide more detail info?

**Comment by eva-mueller** [comment]
Hi. Thank you for your quick response. 

I fooled myself by defining properties in my new custom profile in `.mvn/settings.xml` which were not consumed later due to other reasons.
Sorry for the superfluous issue.

This extensions works with profiles like a charm 👍
